Month 9/step 1
FayustovNA/stellar-burgers pull request #5
Opened 2023-02-23 11:27 UTC by FayustovNA

2023-02-23 12:23 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- Вам нужно добавить файл `.gitignore` в проект;

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- <https://disk.yandex.com/i/oflI07VvZNkcbA>, <https://disk.yandex.com/i/ttmbLErYv1_DSw>,<https://disk.yandex.com/i/AJyGRzgBkwjRAQ> - по макету, здесь не такой большой отступ;

- <https://disk.yandex.com/i/oflI07VvZNkcbA>, <https://disk.yandex.com/i/j6Nor_YxWF3JCA> - по макету у полей ввода на страницах входа и регистрации нет кнопки активации редактирования, эта кнопка есть только у полей ввода на странице профиля. Используйте не компонент `EmailInput`, а просто компонент `Input` с пропсом `type="email"`.

- Вы должны добавлять в хедер запроса `POST /orders`, токен пользователя `Bearer ...`, чтобы сервер понимал что заказ сделал зарегистрированный пользователь (время обработки заказа должно быть в разы больше, если вы всё правильно сделали).

- При перезагрузке страницы, авторизированный пользователь, должен автоматически логинится, если не истёк токен.

- Вы должны вешать обработчик на событие onSubmit элемента form, а не на кнопку;

### **Сделает код лучше:**

- Перенаправьте PR, на ветку из предыдущего PR, либо смержите другие PR в основную ветку `main`. Становится затруднительно проверять работа, т.к. сейчас у вас изменены все файлы проекта, а не только те, которые относятся к заданию.

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-23 12:23 UTC, ArslanDev666 commented on src/pages/forgot-password.js
> +                        </Button>
**Надо исправить:**

Вы должны вешать обработчик на  событие `onSubmit` элемента `form`, а не на кнопку.

2023-02-23 12:23 UTC, ArslanDev666 commented on src/pages/login.js
> +    });
**Можно лучше**

Можно сделать универсальный кастомный хук для контроля любого количества инпутов в любых формах:

```js
export function useForm(inputValues) {
  const [values, setValues] = useState(inputValues);

  const handleChange = event => {
    const { value, name } = event.target;
    setValues({ ...values, [name]: value });
  };
  return { values, handleChange, setValues };
}
```

Этот код помещают в отдельный файл useForm.js в папке hooks и импортируют функцию туда, где нужно контролировать инпуты

И Вам не нужно будет теперь вручную создавать функции обработки инпутов и т д. Все будет в одной строчке кода:

```js
const { values, handleChange, setValues } = useForm({...});
```

2023-02-23 12:23 UTC, ArslanDev666 commented on src/pages/login.js
> +                        <Button htmlType="button" type="primary" size="medium" onClick={handleSubmit}>
**Надо исправить:**

Вы должны вешать обработчик на событие `onSubmit` элемента `form`, а не на кнопку.

2023-02-23 12:23 UTC, ArslanDev666 commented on src/pages/registration.js
> +                <form className={styles.editformregister} onSubmit={(e) => handleSubmit(e)}>
**Можно лучше:**

Тут можно написать просто `onSubmit={handleSubmit}`

2023-02-23 12:23 UTC, ArslanDev666 commented on src/services/action/auth.js
> +                    console.log(res)
**Надо исправить:**

Здесь и далее.

В приложении не должно быть консоль логов или дебаггеров. Вместо console.log используйте console.error() для ошибок.

2023-02-23 12:23 UTC, ArslanDev666 commented on src/services/action/auth.js
> +            })
**Надо исправить:**

Вы должны учесть, что время жизни токена, может закончится, и тогда у вас тут будет ошибка.

Когда время жизни токена закончится, вам нужно его обновить, для этого лучше создать обёртку над запросом: 

```js
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-02-23 12:23 UTC, ArslanDev666 commented on src/services/action/auth.js
> +export function updateUserInfo({ name, email, password }) {
**Надо исправить:**

Вы должны учесть, что время жизни токена, может закончится, и тогда у вас тут будет ошибка.

Когда время жизни токена закончится, вам нужно его обновить, для этого лучше создать обёртку над запросом: 

```js
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkReponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkReponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-02-23 12:23 UTC, ArslanDev666 commented on src/services/reducers/burger-constructor.js
> +    counters: {},
**Надо исправить:**

Если значения нет, то нужно использовать null, а не пустой объект.

2023-02-23 14:51 UTC, FayustovNA commented on src/services/reducers/burger-constructor.js
> +    counters: {},
Тогда сыпется весь стейт и не проходит рендер первой страницы.

2023-02-24 08:34 UTC, ArslanDev666 commented on src/services/reducers/burger-constructor.js
> +    counters: {},
В этом случае можно сделать проверку))

2023-02-24 08:44 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Практически все замечания были исправлены;

### **Но есть несколько замечаний, которые нужно исправить:**

- Название файла `.gitignore` должно начинаться с точки;

- Вам нужно удалить дублирующиеся файлы `.js` в компонентах;

- <https://disk.yandex.com/i/Smu2mYKdN0uMLA> - по макету, здесь не такой большой отступ, и тоже самое на страницах, восстановить пароль и регистрация;

2023-02-24 17:36 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

2023-02-25 05:07 UTC, FayustovNA commented
step 1 done

2023-02-25 05:24 UTC, merged